"""
Pydantic Schemas for Text-to-SQL Agent Pipeline.
Defines structured output types for Schema Linking and SQL Generation.
"""

from pydantic import BaseModel, Field


class SchemaLink(BaseModel):
    """
    SchemaLink output structure representing the target tables and columns
    selected by the Schema Selector agent for a given user query.
    """
    tables: list[str] = Field(
        description="Lista de nomes de tabelas necessárias para responder à pergunta (ex: ['dim_movies', 'bridge_movie_genre', 'dim_genres'])"
    )
    columns: list[str] = Field(
        description="Lista de colunas necessárias identificadas no formato 'tabela.coluna' ou 'coluna'"
    )
    reasoning: str = Field(
        description="Justificativa lógica da escolha das tabelas e colunas, incluindo o mapeamento dos relacionamentos N:N via tabelas bridge_*"
    )


class SQLResult(BaseModel):
    """
    SQLResult output structure generated by the SQL Generator agent.
    Includes reasoning, generated SQL query string, and confidence score.
    """
    reasoning: str = Field(
        description="Explicação passo a passo da estratégia utilizada para construir a query SQL, incluindo resultados das ferramentas (get_distinct_values, execute_query)"
    )
    sql: str = Field(
        description="Consulta SQL limpa e válida no dialeto SQLite, pronta para execução"
    )
    confidence: float = Field(
        description="Nível de confiança da consulta SQL gerada, entre 0.0 e 1.0"
    )
